CREATE TABLE [dbo].[User]
(
	    [Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Salt] VARBINARY(100) NOT NULL,
    [Password] VARBINARY(100) NOT NULL,
    [FirstName] NVARCHAR(100) NOT NULL,
    [LastName] NVARCHAR(100) NOT NULL,
    [Email] NVARCHAR(100) NOT NULL
)
